repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.13.1
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts

  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.6.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-yaml
  #     - id: check-json

  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.6.0
  #   hooks:
  #     - id: check-yaml
  #       files: \.(yml|yaml)$

  # - repo: https://github.com/markdownlint/markdownlint
  #   rev: v0.12.0
  #   hooks:
  #     - id: markdownlint

  # - repo: local
  #   hooks:
  #     - id: helm-lint
  #       name: Helm Lint
  #       entry: helm lint
  #       language: system
  #       files: ^charts/
  #       types: [file]
