{{- if .Values.backend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guardrails.fullname" . }}-backend
  labels:
    {{- include "guardrails.backendLabels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "guardrails.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "guardrails.backendLabels" . | nindent 8 }}
        {{- with .Values.backend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if gt (len .Values.imagePullSecrets) 0 }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
          {{- if .name }}
        - name: {{ .name }}
          {{- else }}
        - name: whylabs-{{ $.Release.Name }}-registry-credentials
          {{- end }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "guardrails.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          {{- if .Values.backend.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.backend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.backend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            - name: temp-dir
              mountPath: /tmp
            {{- if .Values.extraVolumeMounts }}
              {{- with .extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
      volumes:
        - name: temp-dir
          emptyDir: {}
      {{- if .Values.extraVolumes }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
