{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "guardrails.fullname" . }}
  labels:
    {{- include "guardrails.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "guardrails.fullname" . }}
  minReplicas: {{ default 1 .Values.autoscaling.minReplicas }}
  maxReplicas: {{ default 20 .Values.autoscaling.maxReplicas }}
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- with .scaleUp }}
    scaleUp:
      {{- with .policies }}
      policies:
        {{- range . }}
        - type: {{ .type }}
          value: {{ tpl (toString .value) $ | int }}
          periodSeconds: {{ .periodSeconds | int }}
        {{- end }}
      {{- end }}
      {{- with .selectPolicy }}
      selectPolicy: {{ . }}
      {{- end }}
      {{- with .stabilizationWindowSeconds }}
      stabilizationWindowSeconds: {{ . | int }}
      {{- end }}
    {{- end }}
    {{- with .scaleDown }}
    scaleDown:
      {{- with .policies }}
      policies:
        {{- range . }}
        - type: {{ .type }}
          value: {{ tpl (toString .value) $ | int }}
          periodSeconds: {{ .periodSeconds | int }}
        {{- end }}
      {{- end }}
      {{- with .selectPolicy }}
      selectPolicy: {{ . }}
      {{- end }}
      {{- with .stabilizationWindowSeconds }}
      stabilizationWindowSeconds: {{ . | int}}
      {{- end }}
    {{- end }}
  {{- end }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
