{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "guardrails.fullname" . }}-backend
  labels:
    {{- include "guardrails.backendLabels" . | nindent 4 }}
  {{- if .Values.backend.service.annotations }}
  annotations:
    {{- .Values.backend.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  selector:
    {{- include "guardrails.backendSelectorLabels" . | nindent 4 }}
{{- end -}}