{{- if .Values.cache.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    {{- include "guardrails.cacheSelectorLabels" . | nindent 4 }}
{{- end }}
