apiVersion: v1
kind: Service
metadata:
  name: {{ include "whylogs.fullname" . }}
  labels:
    {{- include "whylogs.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "whylogs.selectorLabels" . | nindent 4 }}
