apiVersion: v1
kind: Service
metadata:
  name: {{ include "langkit.fullname" . }}
  labels:
    {{- include "langkit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
  selector:
    {{- include "langkit.selectorLabels" . | nindent 4 }}
