name: Publish Helm Chart

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Package Helm Chart
        working-directory: ${{ github.workspace }}
        run: |
          helm package charts/langkit

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            docker login ghcr.io \
            -u ${{ github.repository_owner }} \
            --password-stdin

      - name: Publish Helm Chart
        working-directory: ${{ github.workspace }}
        run: |
          chart=$(find . -name '*.tgz' | sort -r | head -n 1)
          version=$(basename $chart | sed 's/\.tgz//')
          
          docker tag $chart \
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/$version
          
          docker push \
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/$version
